---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readr)
library(glue)
```

```{r}
prob_data <- data.frame(read_csv("~/Desktop/nba_betting/538_nba_data_2020_11_21.csv"
                                 ,col_type=cols(.default="?"
                                                ,playoff="c"
                                                ,'carm-elo1_pre'="n"
                                                ,'carm-elo2_pre'="n"
                                                ,'carm-elo_prob1'="n"
                                                ,'carm-elo_prob2'="n"
                                                ,'carm-elo1_post'="n"
                                                ,'carm-elo2_post'="n"
                                                ,raptor1_pre="n"
                                                ,raptor2_pre="n"
                                                ,raptor_prob1="n"
                                                ,raptor_prob2="n"
                                                )))
prob_data<-prob_data[prob_data$season>=2009,]
```

```{r}
odds_data<-read_csv("~/Desktop/nba_betting/csv_betting_data/nba odds 2008-09.csv")
odds_data$season_start_year<-2008

#file_name<-"~/Desktop/nba_betting/csv_betting_data/nba odds 2008-09.csv"

for (i in 9:19){
  start_year<-as.character(i)
  end_year<-as.character(i+1)
  
  if (nchar(start_year)==1){start_year<-paste0("0",start_year)}
  if (nchar(end_year)==1){end_year<-paste0("0",end_year)}
  
  file_name<-glue("~/Desktop/nba_betting/csv_betting_data/nba odds 20{start_year}-{end_year}.csv")
  spc_file<-read_csv(file_name)
  spc_file<-spc_file[,colSums(is.na(spc_file))<nrow(spc_file)]
  
  spc_file<-spc_file[!rowSums(is.na(spc_file))==ncol(spc_file),]
  
  spc_file$season_start_year<-2000+i
  
  odds_data<-rbind(odds_data,spc_file)
}

```

```{r}
#Pre-processing of odds_data to get it ready to be joined with
odds_data<-data.frame(odds_data)
odds_data$Date<-as.character(odds_data$Date)

odds_data$day<-substr(odds_data$Date,nchar(odds_data$Date)-1,nchar(odds_data$Date))
odds_data$month<-substr(odds_data$Date,1,nchar(odds_data$Date)-2)

odds_data$year<-NA

first_year_occ<-match(unique(odds_data$season_start_year),odds_data$season_start_year)
odds_data$year[first_year_occ]<-odds_data$season_start_year[first_year_occ]

for (i in 1:nrow(odds_data)){
  
  if (is.na(odds_data[i,"year"])){
    if(odds_data[i,"month"]>=odds_data[(i-1),"month"]){
      odds_data[i,"year"]<-odds_data[(i-1),"year"]
    } else {
      odds_data[i,"year"]<-odds_data[(i-1),"year"]+1
    }
  }
}

odds_data$game_date<-as.Date(paste0(odds_data$year,'-',odds_data$month,'-',odds_data$day))
```

```{r}
odds_data<-odds_data[,c("game_date","Team","VH","X1st","X2nd","X3rd","X4th","Final","Open","Close","ML","X2H")]
```

```{r}
both_cols<-c("date","season","neutral","playoff")

team_1_cols<-c("team1","elo1_pre","elo_prob1","elo1_post","carm.elo1_pre","carm.elo_prob1","carm.elo1_post","raptor1_pre","raptor_prob1","score1")

team_2_cols<-c("team2","elo2_pre","elo_prob2","elo2_post","carm.elo2_pre","carm.elo_prob2","carm.elo2_post","raptor2_pre","raptor_prob2","score2")

prob_data_team1<-prob_data[,c(both_cols,team_1_cols,team_2_cols)]
prob_data_team2<-prob_data[,c(both_cols,team_2_cols,team_1_cols)]

names_both_cols<-c("date","season","neutral","playoff")
generic_names<-c("team","elo_pre","elo_prob","elo_post","carm.elo_pre","carm.elo_prob","carm.elo_post","raptor_pre","raptor_prob","score")
self_names<-paste0("self_",generic_names)
opp_names<-paste0("opp_",generic_names)

colnames(prob_data_team1)<-c(names_both_cols,self_names,opp_names)
colnames(prob_data_team2)<-c(names_both_cols,self_names,opp_names)

prob_team_data<-rbind(prob_data_team1,prob_data_team2)
```

